---
# handlers file for cuttlefish-app
- name: nginx restart
  service: name=nginx state=restarted

- name: nginx reload
  service: name=nginx state=reloaded

- name: postgresql restart
  service:
    name: postgresql
    state: restarted
