---
- hosts: all
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      assert:
        that: ansible_version.major == 2 and ansible_version.minor == 5
        msg: >
          "This currently works with Ansible 2.5"

- hosts: all
  become: true
  #user: root
  roles:
    - {role: deploy-user, github_users: ['mlandauer', 'henare', 'jamezpolley']}
    - cuttlefish-app
